language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - composer self-update
    - composer install --dev
    - cp ./config/parameters.yaml.dist ./config/parameters.yaml

script: ./vendor/bin/phpunit
